### ISSUE TITLE
vg_requireKey = true; not work

### ISSUE THREAD

**Issue by ShareWoodZ** [oiad/virtualGarage#21]
option:
vg_requireKey = true; // Require the player to have the key when storing a locked vehicle.
not work
im can store spawn vehicles. (id=0)
https://youtu.be/McXoHlrsuOA

**Comment by oiad** [comment]
Hello,
`vg_requireKey` was never intended to be able to deny storing UID 0 vehicles, it was only intended to be used with locked vehicles so people required the key.
