### ISSUE TITLE
Строительство вертолетных площадок

### ISSUE THREAD

**Issue by GACI** [oiad/virtualGarage#22]
Tell me where to add these "helipad_civil_kit, helipad_rescue_kit, helipad_army_kit, helipad_cross_kit, helipad_parkborder_kit" items so that players can build a helipad.

**Comment by GACI** [comment]
Tell me where to add these "helipad_civil_kit, helipad_rescue_kit, helipad_army_kit, helipad_cross_kit, helipad_parkborder_kit" items so that players can build a helipad.

**Comment by AirwavesMan** [comment]
You have to add these to a trader.

**Comment by GACI** [comment]
What file is it?

**Comment by GACI** [comment]
What file is it?

**Comment by GACI** [comment]
> добавить их трейдеру.

add to which trader?

**Comment by GACI** [comment]
Tell me where to add (register) these items "helipad_civil_kit, helipad_rescue_kit, helipad_army_kit, helipad_cross_kit, helipad_parkborder_kit" so that players can build a helipad.
