### ISSUE TITLE
If vehicle painted, there is a 5sec delay to recover colors: HOTFIX

### ISSUE THREAD

**Issue by ghost** [oiad/virtualGarage#7]
Hello @salival,
As was reported to me (and from my personal experience), there is annoying delay to recolor vehicles when spawning them from garage :)

Hotfix for this issue should be pretty easy:

go to [**server_spawnVehicle file, line 147**](https://github.com/oiad/virtualGarage/blob/7d78468b37916ae641648eacec93c8ac5c1087d3/dayz_server/compile/garage/server_spawnVehicle.sqf#L147) and just add command:
`processInitCommands;`
This will process statements stored using `setVehicleInit` and you will get colored vehicles immediately with no delay when spawning them from virtual garage.

Tested on my local dev server, passed.

**Thx for your great work buddy!**

Cheers...
iben

**Comment by oiad** [comment]
Thanks for the heads up, fixed here: https://github.com/oiad/virtualGarage/commit/3b18c7f8a6e00c04c338fde5f3bd4ae38245eca5
